/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phuket_tour_fdkaac_encoder_AudioEncoder */

#ifndef _Included_com_phuket_tour_fdkaac_encoder_AudioEncoder
#define _Included_com_phuket_tour_fdkaac_encoder_AudioEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phuket_tour_fdkaac_encoder_AudioEncoder
 * Method:    encode
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_fdkaac_encoder_AudioEncoder_encode
  (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
